#ifndef IS_IT_SHOW_PRESENTED_COURSE_TYPE_TWO_COMMAND_HPP
#define IS_IT_SHOW_PRESENTED_COURSE_TYPE_TWO_COMMAND_HPP
#include "global.hpp"
bool is_it_show_presented_course_type_two_command(string command);
#endif